### ISSUE TITLE
loading a preset

### ISSUE THREAD

**Issue by rinaldi6109** [Eliastik/page-shadow#4]
When I load a preset in the settings window, everytime the first preset name is shown.

**Comment by Eliastik** [comment]
This issue is due to the fact that when you load a preset in that window, all the settings are refreshed including the preset selector which is constructed by the function `loadPresetSelect(selectId)` in the [utils.js](https://github.com/Eliastik/page-shadow/blob/master/src/js/util.js) script. This function is also used when you load a preset in the Advanced settings page which haven't this issue. This issue is just graphical, and doesn't affect the loading of the preset selected.

**Comment by Eliastik** [comment]
Fixed in commit 3ef3d54

**Comment by Eliastik** [comment]
Fixed in commit 3ef3d54
